"""
IMPORTANT DISCLAIMER

This script was entirely generated by ChatGPT, save for a couple of lines here and there.

It is very specifically designed to read the "Museum_54_patches" mesh and split it in a
custom-designed way. In other words, it is a tool for extremely specific re-meshing which
certainly would not work in almost any other re-meshing context.

It also serves as a peculiar "look into ChatGPT's mind". Due to weird circumstances, this
code was originally written by ChatGPT for its internal use (to be run in its server-side
environment), but over the course of the conversation it was revealed to me. As such, it
is extremely non-pythonic Python code, basically not intended to be human-readable. I only
altered some small parts of the script in order to make it run in my own environment.
"""

from pathlib import Path
import re, math, sys, os
from collections import defaultdict, Counter
import numpy as np
import colorsys

AREA_THRESHOLD = 5.0

# I/O (relative to working dir)
OBJ_IN = Path("mesh.obj")
MTL_IN = Path("mesh.mtl")

if not OBJ_IN.exists() or not MTL_IN.exists():
    sys.exit("Error: mesh.obj and/or mesh.mtl not found.")

MTL_NAME_RE = re.compile(r"^Patch_(\d+)_Mat_(.+)$")
def ascii_of(name: str):
    m = MTL_NAME_RE.match(name or "")
    return m.group(2) if m else None
def idx_of(name: str):
    m = MTL_NAME_RE.match(name or "")
    return int(m.group(1)) if m else 10**9

# ---------- Parse ----------
def parse_obj(path: Path):
    verts = []
    faces_by_mtl = defaultdict(list)
    vertex_lines = []
    mtllib = None
    cur_mtl = None
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        s = raw.strip()
        if not s: continue
        if s.startswith("mtllib "):
            mtllib = s.split(None,1)[1].strip()
        elif s.startswith("v "):
            vertex_lines.append(raw)
            x,y,z = map(float, s.split()[1:4])
            verts.append((x,y,z))
        elif s.startswith("usemtl "):
            cur_mtl = s.split(None,1)[1].strip()
        elif s.startswith("f "):
            if cur_mtl is None: cur_mtl="__NO_MATERIAL__"
            idxs=[]
            for p in s.split()[1:]:
                vi = p.split("/")[0]
                if not vi: continue
                vi = int(vi)
                if vi < 0: vi = len(verts) + 1 + vi
                idxs.append(vi-1)
            if len(idxs)<3: continue
            if len(idxs)==3:
                faces_by_mtl[cur_mtl].append(tuple(idxs))
            else:
                v0=idxs[0]
                for i in range(1,len(idxs)-1):
                    faces_by_mtl[cur_mtl].append((v0, idxs[i], idxs[i+1]))
    return np.array(verts,float), faces_by_mtl, vertex_lines, mtllib

def parse_mtl_blocks(path: Path):
    blocks = []
    cur = {"name": None, "lines": []}
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        if line.strip().lower().startswith("newmtl "):
            if cur["name"] is not None or cur["lines"]:
                blocks.append(cur)
            cur = {"name": line.strip().split(None,1)[1].strip(), "lines":[line]}
        else:
            cur["lines"].append(line)
    if cur["name"] is not None or cur["lines"]:
        blocks.append(cur)
    return blocks

def ascii_to_template(blocks):
    m = {}
    for b in blocks:
        nm = b["name"] or ""
        k = MTL_NAME_RE.match(nm)
        if not k: continue
        asc = k.group(2)
        if asc in m: continue
        m[asc] = [ln for ln in b["lines"] if not ln.strip().lower().startswith("newmtl ")]
    return m

def extract_kd(props_lines):
    for ln in props_lines:
        s = ln.strip()
        if s.lower().startswith("kd "):
            parts = s.split()
            if len(parts)>=4:
                try:
                    r,g,b = float(parts[1]), float(parts[2]), float(parts[3])
                    return (r,g,b)
                except:
                    pass
    return (0.8,0.8,0.8)

# ---------- Geometry ----------
def area_normal(V, tris):
    n = np.zeros(3, float)
    for a,b,c in tris:
        p,q,r = V[a], V[b], V[c]
        n += 0.5*np.cross(q-p, r-p)
    L = np.linalg.norm(n)
    return (n/L) if L>0 else np.array([0,0,1.0], float)

def boundary_loop(tris):
    E = Counter()
    for a,b,c in tris:
        for u,v in ((a,b),(b,c),(c,a)):
            if u>v: u,v=v,u
            E[(u,v)] += 1
    bound = [(u,v) for (u,v),cnt in E.items() if cnt==1]
    if not bound: return []
    adj = defaultdict(list)
    for u,v in bound:
        adj[u].append(v); adj[v].append(u)
    start = min(adj.keys())
    loop=[start]; prev=None; cur=start
    for _ in range(len(adj)+10):
        nbrs=adj[cur]
        nxt = nbrs[0] if (len(nbrs)==1 or nbrs[0]!=prev) else nbrs[1]
        if nxt==start: loop.append(nxt); break
        loop.append(nxt); prev,cur=cur,nxt
    if loop and loop[-1]==loop[0]: loop=loop[:-1]
    return loop

def plane_basis(V, loop, tris):
    p0 = V[loop[0]]
    n = area_normal(V, tris)
    u = V[loop[1]] - p0
    Lu = np.linalg.norm(u)
    if Lu<1e-9:
        for k in range(2,len(loop)):
            u = V[loop[k]] - p0; Lu=np.linalg.norm(u)
            if Lu>=1e-9: break
    if Lu<1e-12: u = np.array([1.0,0.0,0.0]); Lu=1.0
    u /= Lu
    v = np.cross(n,u); vn=np.linalg.norm(v)
    v = v/vn if vn>1e-12 else np.array([0.0,1.0,0.0])
    if np.dot(np.cross(u,v), n) < 0:
        v = -v
    return p0,u,v,n

def project(V, p0,u,v, idxs):
    return np.array([[np.dot(V[i]-p0,u), np.dot(V[i]-p0,v)] for i in idxs], float)

def simplify_colinear(P, tol=1e-6):
    n=len(P)
    if n<=3: return P
    keep=[]
    for i in range(n):
        a=P[(i-1)%n]; b=P[i]; c=P[(i+1)%n]
        v1=b-a; v2=c-b
        n1=np.linalg.norm(v1); n2=np.linalg.norm(v2)
        if n1<tol or n2<tol: continue
        cr=abs(v1[0]*v2[1]-v1[1]*v2[0]); dot=v1@v2
        if n1*n2>0 and cr/(n1*n2)<=1e-8 and dot>0: continue
        keep.append(b)
    return np.array(keep,float)

def is_axis_aligned(P, tol=1e-5):
    for i in range(len(P)):
        a=P[i]; b=P[(i+1)%len(P)]
        d=b-a
        if (abs(d[0])>tol) and (abs(d[1])>tol):
            return False
    return True

def is_rectangle(P):
    P = simplify_colinear(P)
    if len(P)!=4: return False
    e=[]
    for i in range(4):
        v=P[(i+1)%4]-P[i]; l=np.linalg.norm(v)
        if l<=1e-6: return False
        e.append(v/l)
    for i in range(4):
        if abs(np.dot(e[i], e[(i+1)%4]))>1e-3: return False
    return True

def poly_area(P):
    a=0.0
    for i in range(len(P)):
        x1,y1=P[i]; x2,y2=P[(i+1)%len(P)]
        a += x1*y2 - x2*y1
    return 0.5*a

def make_ccw(P):
    return P if poly_area(P)>0 else P[::-1].copy()

def point_in_polygon(pt, P):
    x,y=pt; wn=0
    for i in range(len(P)):
        x0,y0=P[i]; x1,y1=P[(i+1)%len(P)]
        if y0 <= y < y1 and (x1-x0)*(y-y0) - (x-x0)*(y1-y0) > 0: wn += 1
        elif y1 <= y < y0 and (x1-x0)*(y-y0) - (x-x0)*(y1-y0) < 0: wn -= 1
    return wn != 0

def classify_polygon(V, tris):
    loop = boundary_loop(tris)
    if not loop: return "nonconvex_rectilinear", loop
    p0,u,v,n = plane_basis(V, loop, tris)
    P = simplify_colinear(project(V, p0,u,v, loop))
    if is_rectangle(P): return "rectangle", loop
    if len(tris)==8:
        cnt=Counter()
        for t in tris:
            for vi in t: cnt[vi]+=1
        if len([k for k,c in cnt.items() if c==8])==1:
            return "octagon", loop
    return "nonconvex_rectilinear", loop

def is_horizontal(V, tris):
    zs = [V[i][2] for t in tris for i in t]
    return (max(zs)-min(zs))<=1e-6

# ---------- Builders ----------
class Builder:
    def __init__(self, V0):
        self.V0 = np.array(V0,float)
        self.newV = []
        self.faces = defaultdict(list)  # mtl -> list of (a,b,c)
        self.used_indices=set()
        self.next_idx=0
        self.tol=1e-3
        self.created_mtls = []  # preserve creation order
    def reserve_from_original(self, faces_by_mtl):
        mx=0
        for nm in faces_by_mtl.keys():
            m=MTL_NAME_RE.match(nm)
            if not m: continue
            i=int(m.group(1)); self.used_indices.add(i); mx=max(mx,i)
        self.next_idx=mx+1
    def new_mtl(self, ascii_str):
        while self.next_idx in self.used_indices: self.next_idx+=1
        i=self.next_idx; self.used_indices.add(i); self.next_idx+=1
        name = f"Patch_{i}_Mat_{ascii_str}"
        self.created_mtls.append(name)
        return name
    def addV(self,p):
        self.newV.append(np.array(p,float))
        return len(self.V0)+len(self.newV)-1
    def add_faces(self, mtl, tris):
        self.faces[mtl].extend(tris)
    def collapse(self):
        pts=[tuple(v) for v in self.V0]+[tuple(v) for v in self.newV]
        def key(p): return (round(p[0]/self.tol), round(p[1]/self.tol), round(p[2]/self.tol))
        mapping={}; k2n={}; out=[]
        for i,p in enumerate(pts):
            k=key(p)
            if k in k2n: mapping[i]=k2n[k]
            else: k2n[k]=len(out); out.append(p); mapping[i]=k2n[k]
        out=np.array(out,float)
        rem=defaultdict(list)
        for mtl, T in self.faces.items():
            for (a,b,c) in T:
                a=mapping[a]; b=mapping[b]; c=mapping[c]
                if a==b or b==c or c==a: continue
                rem[mtl].append((a,b,c))
        self.faces=rem
        return out

def orient_tri_indices_to_normal(P0,P1,P2, n_vec):
    tn = np.cross(P1-P0, P2-P0)
    return (0,2,1) if np.dot(tn, n_vec) < 0 else (0,1,2)

def orient_tri_to_normal(Va,Vb,Vc, n):
    tn = np.cross(Vb-Va, Vc-Va)
    return (Va,Vc,Vb) if np.dot(tn, n) < 0 else (Va,Vb,Vc)

def lattice_counts(L):
    return 1 if L<=np.sqrt(AREA_THRESHOLD) else int(math.floor(L/np.sqrt(AREA_THRESHOLD)))+1

# ---------- Emitters (collector adds created mtl names for per-parent grouping) ----------
def emit_rectangle_grid(builder, ascii_str, p0,u,v,n, R4, material_name=None, collector=None):
    R4 = simplify_colinear(R4)
    s=int(np.argmin(R4[:,0] + 1e-7*R4[:,1]))
    R = np.vstack([R4[(i)%4] for i in range(s,s+4)])
    e0=R[1]-R[0]; e1=R[2]-R[1]
    A=np.linalg.norm(e0); B=np.linalg.norm(e1)
    nA, nB = lattice_counts(A), lattice_counts(B)
    dA=e0/nA; dB=e1/nB
    x0,y0=R[0]; P00 = p0 + x0*u + y0*v
    for i in range(nA):
        for j in range(nB):
            P_00=P00 + i*dA[0]*u + i*dA[1]*v + j*dB[0]*u + j*dB[1]*v
            P_10=P_00 + dA[0]*u + dA[1]*v
            P_11=P_10 + dB[0]*u + dB[1]*v
            P_01=P_00 + dB[0]*u + dB[1]*v
            ia=builder.addV(P_00); ib=builder.addV(P_10); ic=builder.addV(P_11); idd=builder.addV(P_01)
            A0,B0,C0,D0 = np.array(P_00), np.array(P_10), np.array(P_11), np.array(P_01)
            order = orient_tri_indices_to_normal(A0,B0,C0, n)
            tri1 = ( (ia,ib,ic)[order[0]], (ia,ib,ic)[order[1]], (ia,ib,ic)[order[2]] )
            order = orient_tri_indices_to_normal(A0,C0,D0, n)
            tri2 = ( (ia,ic,idd)[order[0]], (ia,ic,idd)[order[1]], (ia,ic,idd)[order[2]] )
            mtl = material_name or builder.new_mtl(ascii_str)
            builder.add_faces(mtl, [tri1, tri2])
            if collector is not None: collector.add(mtl)

def emit_octagon(builder, ascii_str, V, tris, collector=None):
    n_vec = area_normal(V, tris)

    # Find the area of one of the triangles; if it's low, split them all in 4
    a, b, c = tris[0]
    A, B, C = V[a], V[b], V[c]
    area = 0.5 * np.linalg.norm(np.cross(B-A, C-A))

    if area <= AREA_THRESHOLD:
        for a,b,c in tris:
            A,B,C = V[a],V[b],V[c]
            AA,BB,CC = orient_tri_to_normal(A,B,C, n_vec)
            def id_of(P):
                da,db,dc = np.linalg.norm(P-A), np.linalg.norm(P-B), np.linalg.norm(P-C)
                return a if da<=db and da<=dc else (b if db<=dc else c)
            tri = (id_of(AA), id_of(BB), id_of(CC))
            mtl = builder.new_mtl(ascii_str)
            builder.add_faces(mtl, [tri])
            if collector is not None: collector.add(mtl)
        return
    for a,b,c in tris:
        A,B,C = V[a],V[b],V[c]
        Mab = 0.5*(A+B)
        Mbc = 0.5*(B+C)
        Mca = 0.5*(C+A)
        smalls = [
            (A,   Mab, Mca),
            (B,   Mbc, Mab),
            (C,   Mca, Mbc),
            (Mab, Mbc, Mca),
        ]
        for P0,P1,P2 in smalls:
            i0 = builder.addV(P0); i1 = builder.addV(P1); i2 = builder.addV(P2)
            order = orient_tri_indices_to_normal(np.array(P0), np.array(P1), np.array(P2), n_vec)
            tri = ( (i0,i1,i2)[order[0]], (i0,i1,i2)[order[1]], (i0,i1,i2)[order[2]] )
            mtl = builder.new_mtl(ascii_str)
            builder.add_faces(mtl, [tri])
            if collector is not None: collector.add(mtl)

def emit_rectangle_no_grid(builder, ascii_str, p0,u,v,n, R4, material_name=None, collector=None):
    R4 = simplify_colinear(R4)
    s=int(np.argmin(R4[:,0] + 1e-7*R4[:,1]))
    R = np.vstack([R4[(i)%4] for i in range(s,s+4)])
    x0,y0=R[0]; x1,y1=R[1]; x2,y2=R[2]; x3,y3=R[3]
    P0 = p0 + x0*u + y0*v
    P1 = p0 + x1*u + y1*v
    P2 = p0 + x2*u + y2*v
    P3 = p0 + x3*u + y3*v
    i0=builder.addV(P0); i1=builder.addV(P1); i2=builder.addV(P2); i3=builder.addV(P3)
    A0,B0,C0,D0 = np.array(P0),np.array(P1),np.array(P2),np.array(P3)
    order = orient_tri_indices_to_normal(A0,B0,C0, n)
    tri1 = ( (i0,i1,i2)[order[0]], (i0,i1,i2)[order[1]], (i0,i1,i2)[order[2]] )
    order = orient_tri_indices_to_normal(A0,C0,D0, n)
    tri2 = ( (i0,i2,i3)[order[0]], (i0,i2,i3)[order[1]], (i0,i2,i3)[order[2]] )
    mtl = material_name or builder.new_mtl(ascii_str)
    builder.add_faces(mtl, [tri1, tri2])
    if collector is not None: collector.add(mtl)

# ---------- Horizontal L: exact, non-overlapping, full-coverage ----------
def split_horizontal_L_into_two_rects_exact(V, tris):
    loop = boundary_loop(tris)
    p0,u,v,n = plane_basis(V, loop, tris)
    P = simplify_colinear(project(V, p0,u,v, loop))
    P = make_ccw(P)
    if not is_axis_aligned(P):
        raise RuntimeError("Expected rectilinear horizontal polygon")
    idx_reflex = None
    for i in range(len(P)):
        a=P[(i-1)%len(P)]; b=P[i]; c=P[(i+1)%len(P)]
        v1=b-a; v2=c-b
        if v1[0]*v2[1]-v1[1]*v2[0] < 0:
            idx_reflex = i; break
    if idx_reflex is None:
        raise RuntimeError("No reflex vertex for L-shape")
    x1,y1 = P[idx_reflex]
    xs = sorted(set([round(float(x),6) for x,_ in P]))
    ys = sorted(set([round(float(y),6) for _,y in P]))
    def three_levels(vals, mid):
        lo = min(vals); hi = max(vals)
        midv = min(vals, key=lambda v: abs(v-mid))
        return lo, midv, hi
    x0, xm, x2 = three_levels(xs, x1)
    y0, ym, y2 = three_levels(ys, y1)
    Q = {
        "Q00": ( (x0,xm), (y0,ym) ),
        "Q10": ( (xm,x2), (y0,ym) ),
        "Q01": ( (x0,xm), (ym,y2) ),
        "Q11": ( (xm,x2), (ym,y2) ),
    }
    def center(cell):
        (xa,xb),(ya,yb)=cell
        return np.array([ (xa+xb)/2.0, (ya+yb)/2.0 ])
    def pinp(pt): return point_in_polygon(pt, P)
    inside = {k: pinp(center(v)) for k,v in Q.items()}
    if sum(1 for v in inside.values() if v) != 3:
        eps=1e-7
        def pinp_eps(pt):
            dxdy = [(0,0),(eps,0),(-eps,0),(0,eps),(0,-eps)]
            return any(point_in_polygon(pt+np.array([dx,dy]), P) for dx,dy in dxdy)
        inside = {k: pinp_eps(center(v)) for k,v in Q.items()}
    missing = [k for k,v in inside.items() if not v]
    if len(missing)!=1:
        raise RuntimeError(f"L-shape should have exactly one missing quadrant; got {missing}")
    miss = missing[0]
    if     miss=="Q10":  R1=((x0,xm),(y0,ym)); R2=((x0,x2),(ym,y2))
    elif   miss=="Q01":  R1=((x0,x2),(y0,ym)); R2=((xm,x2),(ym,y2))
    elif   miss=="Q00":  R1=((xm,x2),(y0,ym)); R2=((x0,x2),(ym,y2))
    elif   miss=="Q11":  R1=((x0,x2),(y0,ym)); R2=((x0,xm),(ym,y2))
    else:
        raise RuntimeError("Unexpected missing quadrant key")
    def rect_poly(R):
        (xa,xb),(ya,yb)=R
        return np.array([[xa,ya],[xb,ya],[xb,yb],[xa,yb]], float)
    return p0,u,v,n,rect_poly(R1),rect_poly(R2)

# ---------- Vertical histogram ----------
def split_vertical_histogram_into_bars(V, tris, loop):
    bestL=-1; best=None
    for i in range(len(loop)):
        a,b=loop[i],loop[(i+1)%len(loop)]
        v=V[b]-V[a]
        if abs(v[2])<=1e-6:
            L=np.linalg.norm(v)
            if L>bestL: bestL=L; best=(a,b)
    if best is None:
        p0,u,v,n = plane_basis(V, loop, tris)
        P = simplify_colinear(project(V,p0,u,v, loop))
        return p0,u,v,n,[P]
    a,b=best; base_vec=V[b]-V[a]
    u = base_vec/np.linalg.norm(base_vec)
    n = area_normal(V, tris)
    v = np.cross(n,u); v/=max(1e-12, np.linalg.norm(v))
    p0=V[a]
    P = simplify_colinear(project(V,p0,u,v, loop))
    y0=0.0
    tops=[]
    for i in range(len(P)):
        A,B=P[i],P[(i+1)%len(P)]
        if abs(A[1]-B[1])<=1e-12 and abs(A[1]-y0)>1e-9:
            x0,x1=sorted([A[0],B[0]])
            tops.append((x0,x1,A[1]))
    bars=[]
    for x0,x1,yt in tops:
        cx,cy=(x0+x1)/2.0,(y0+yt)/2.0
        if point_in_polygon(np.array([cx,cy]), P):
            R=np.array([[x0,y0],[x1,y0],[x1,yt],[x0,yt]], float)
            bars.append(R)
    return p0,u,v,n,bars

# ---------- Histogram merge rule (pairwise + chaining) ----------
def apply_histogram_merging_and_emit(builder, ascii_str, p0,u,v,n, bars, collector=None):
    """
    If any bar with height <= 0.5 shares a vertex with any bar with width <= 0.5 * np.sqrt(AREA_THRESHOLD),
    connect them; components (size>=2) get ONE shared material (no grid).
    Others use the ≤ np.sqrt(AREA_THRESHOLD) grid.
    """
    tol = 1e-6
    widths, heights, corners = [], [], []
    for R in bars:
        x0,y0 = R[0]; x1,_ = R[1]; _,yt = R[2]
        widths.append(float(x1 - x0))
        heights.append(float(abs(yt - y0)))
        corners.append([(x0,y0),(x1,y0),(x1,yt),(x0,yt)])
    def share_vertex(i,j):
        for (xi,yi) in corners[i]:
            for (xj,yj) in corners[j]:
                if abs(xi-xj)<=tol and abs(yi-yj)<=tol: return True
        return False
    short  = [h <= 0.5 for h in heights]
    narrow = [w <= 0.5 * np.sqrt(AREA_THRESHOLD) for w in widths]
    nbars = len(bars)
    parent=list(range(nbars))
    def find(a):
        while parent[a]!=a:
            parent[a]=parent[parent[a]]; a=parent[a]
        return a
    def union(a,b):
        ra,rb=find(a),find(b)
        if ra!=rb: parent[rb]=ra
    for i in range(nbars):
        for j in range(i+1, nbars):
            if share_vertex(i,j) and ((short[i] and narrow[j]) or (short[j] and narrow[i])):
                union(i,j)
    comps=defaultdict(list)
    for i in range(nbars):
        comps[find(i)].append(i)
    grouped=set()
    for _, lst in comps.items():
        if len(lst)>=2:
            shared_mat = builder.new_mtl(ascii_str)
            for idx in lst:
                emit_rectangle_no_grid(builder, ascii_str, p0,u,v,n, bars[idx], material_name=shared_mat, collector=collector)
                grouped.add(idx)
            if collector is not None: collector.add(shared_mat)
    for i in range(nbars):
        if i not in grouped:
            emit_rectangle_grid(builder, ascii_str, p0,u,v,n, bars[i], collector=collector)

# ---------- Main ----------
V, faces_by_mtl, vertex_lines, mtllib = parse_obj(OBJ_IN)
mtl_blocks = parse_mtl_blocks(MTL_IN)
ascii_tmpl = ascii_to_template(mtl_blocks)

builder = Builder(V)
builder.reserve_from_original(faces_by_mtl)

classification={}; loops={}
for mtl, tris in faces_by_mtl.items():
    if mtl=="__NO_MATERIAL__": continue
    cat, loop = classify_polygon(V, tris)
    classification[mtl]=cat; loops[mtl]=loop

# Track which new materials came from which ORIGINAL material (per-polygon grouping)
parts_by_parent = defaultdict(set)

for mtl, tris in faces_by_mtl.items():
    if mtl=="__NO_MATERIAL__": continue
    asc = ascii_of(mtl); loop = loops[mtl]; cat = classification[mtl]
    collector = set()
    if cat=="rectangle":
        p0,u,v,n = plane_basis(V, loop, tris)
        R = simplify_colinear(project(V, p0,u,v, loop))
        emit_rectangle_grid(builder, asc, p0,u,v,n, R, collector=collector)
    elif cat=="octagon":
        emit_octagon(builder, asc, V, tris, collector=collector)
    else:
        if is_horizontal(V, tris):
            p0,u,v,n,R1,R2 = split_horizontal_L_into_two_rects_exact(V, tris)
            emit_rectangle_grid(builder, asc, p0,u,v,n, R1, collector=collector)
            emit_rectangle_grid(builder, asc, p0,u,v,n, R2, collector=collector)
        else:
            p0,u,v,n,bars = split_vertical_histogram_into_bars(V, tris, loop)
            apply_histogram_merging_and_emit(builder, asc, p0,u,v,n, bars, collector=collector)
    if collector:
        parts_by_parent[mtl].update(collector)

# Collapse vertices (≤ 0.001)
V2 = builder.collapse()

# ---------- FOUR-COLOR per original polygon (after collapse, before reindex) ----------
def build_adjacency_for_materials(material_names):
    """
    Edge-based adjacency: parts are adjacent iff they share at least one whole edge
    (two common vertex indices) after collapse. This fixes the octagon split case.
    """
    mats = list(material_names)
    edge_to_mats = defaultdict(set)
    # Collect undirected edges per material
    for m in mats:
        for a,b,c in builder.faces.get(m, []):
            for u,v in ((a,b),(b,c),(c,a)):
                if u>v: u,v=v,u
                edge_to_mats[(u,v)].add(m)
    # Build adjacency via shared edges
    adj = {m:set() for m in mats}
    for mats_set in edge_to_mats.values():
        if len(mats_set) >= 2:
            lst = list(mats_set)
            for i in range(len(lst)):
                mi = lst[i]
                for j in range(i+1, len(lst)):
                    mj = lst[j]
                adj[mi].add(mj); adj[mj].add(mi)
    return adj

def dsatur_four_color(adj):
    colors = {}
    nodes = list(adj.keys())
    # Order by degree desc for a good start
    nodes.sort(key=lambda x: -len(adj[x]))
    def smallest_avail(node):
        used = {colors[n] for n in adj[node] if n in colors}
        for c in range(4):
            if c not in used: return c
        return None
    for _ in range(len(nodes)):
        uncolored = [n for n in nodes if n not in colors]
        if not uncolored: break
        def sat(n):
            return len({colors[m] for m in adj[n] if m in colors})
        n_pick = max(uncolored, key=lambda n:(sat(n), len(adj[n])))
        c = smallest_avail(n_pick)
        if c is None:
            # rare fallback
            for c_try in range(4):
                if all(colors.get(nb)!=c_try for nb in adj[n_pick]):
                    c=c_try; break
        if c is None: c=0
        colors[n_pick]=c
    return colors

# Compute color variant index (0..3) per material (pre-reindex)
color_variant = {}
for parent, parts in parts_by_parent.items():
    if not parts: continue
    adj = build_adjacency_for_materials(parts)
    assign = dsatur_four_color(adj)
    color_variant.update(assign)

# --- Reindex materials to 1..M and sort (ensures increasing order in MTL & OBJ)
def reindex_materials_to_sequential(builder):
    used_order = [nm for nm in builder.created_mtls if nm in builder.faces and builder.faces[nm]]
    for nm in builder.faces.keys():
        if nm not in used_order:
            used_order.append(nm)
    mapping={}
    new_faces=defaultdict(list)
    next_id=1
    for old in used_order:
        asc = ascii_of(old) or ""
        new_name = f"Patch_{next_id}_Mat_{asc}"
        mapping[old]=new_name
        next_id += 1
    for old, tris in builder.faces.items():
        new_name = mapping.get(old)
        if new_name is None:
            asc = ascii_of(old) or ""
            new_name = f"Patch_{next_id}_Mat_{asc}"
            mapping[old]=new_name
            next_id += 1
        new_faces[new_name].extend(tris)
    builder.faces = new_faces
    return mapping

old_to_new = reindex_materials_to_sequential(builder)
# carry color assignment through the rename
color_variant = { old_to_new.get(k,k): v for k,v in color_variant.items() }

# ---- MTL ----
def sorted_mtl_names(faces_dict):
    return sorted(faces_dict.keys(), key=idx_of)
new_mtls = sorted_mtl_names(builder.faces)

# Precompute base RGB per ASCII
base_rgb_by_ascii = {asc: extract_kd(lines) for asc,lines in ascii_tmpl.items()}

def hsl_variant(rgb, variant_idx):
    r,g,b = rgb
    # clamp
    r=min(max(r,0.0),1.0); g=min(max(g,0.0),1.0); b=min(max(b,0.0),1.0)
    h,l,s = colorsys.rgb_to_hls(r,g,b)  # HLS in colorsys; L here is "lightness" as in HSL
    if variant_idx == 0:
        l2 = l
    elif variant_idx == 1:
        l2 = l + 0.05
    elif variant_idx == 2:
        l2 = l - 0.05
    elif variant_idx == 3:
        l2 = l + 0.10
    else:
        l2 = l
    l2 = min(max(l2, 0.0), 1.0)
    r2,g2,b2 = colorsys.hls_to_rgb(h, l2, s)
    return (r2,g2,b2)

def recolor_props(props_lines, rgb_out):
    r,g,b = rgb_out
    out=[]
    kd_done=False; ka_done=False; ks_done=False
    for ln in props_lines:
        s = ln.strip().lower()
        if s.startswith("kd "):
            out.append(f"Kd {r:.6f} {g:.6f} {b:.6f}\n"); kd_done=True
        elif s.startswith("ka "):
            out.append(f"Ka {r:.6f} {g:.6f} {b:.6f}\n"); ka_done=True
        elif s.startswith("ks "):
            out.append(f"Ks {r:.6f} {g:.6f} {b:.6f}\n"); ks_done=True
        else:
            out.append(ln if ln.endswith("\n") else ln+"\n")
    if not kd_done: out.append(f"Kd {r:.6f} {g:.6f} {b:.6f}\n")
    if not ka_done: out.append(f"Ka {r:.6f} {g:.6f} {b:.6f}\n")
    if not ks_done: out.append(f"Ks {r:.6f} {g:.6f} {b:.6f}\n")
    return out

mtl_lines=[]
for nm in new_mtls:
    asc = ascii_of(nm) or ""
    props = ascii_tmpl.get(asc, [])
    base_rgb = base_rgb_by_ascii.get(asc, (0.8,0.8,0.8))
    var_idx = color_variant.get(nm, 0)  # default base color if uncolored (e.g., solitary part)
    rgb_out = hsl_variant(base_rgb, var_idx)
    mtl_lines.append(f"newmtl {nm}\n")
    mtl_lines.extend(recolor_props(props, rgb_out))
    mtl_lines.append("\n")
mtl_text = "".join(mtl_lines)

# ---- OBJ ----
# hash_col = 56
# for raw in vertex_lines:
#     if raw.startswith("v ") and "#" in raw:
#         hash_col = raw.index("#"); break
# def fmt_v(idx1, p):
#     s=f"v {p[0]:.6f} {p[1]:.6f} {p[2]:.6f}"
#     pad=max(1, hash_col - len(s))
#     return s + (" " * pad) + f"# {idx1}\n"
# obj_lines=[]
# obj_lines.append(f"mtllib mesh.mtl\n")
# obj_lines.append("################################ Vertices\n")
# for i,p in enumerate(V2, start=1):
#     obj_lines.append(fmt_v(i, p))
# obj_lines.append("################################ Faces\n")
# for nm in new_mtls:  # already 1..M
#     obj_lines.append(f"usemtl {nm}\n")
#     for a,b,c in builder.faces[nm]:
#         obj_lines.append(f"f {a+1} {b+1} {c+1}\n")
# obj_text = "".join(obj_lines)

obj_lines = []
obj_lines.append('mtllib mesh.mtl\n')
line = ''
for i in range(32):
    line += '#'
line += ' Vertices\n'
obj_lines.append(line)

for i, p in enumerate(V2, start=1):
    vertex_line = 'v ' + str(np.round(p[0], 7)) + ' ' + str(np.round(p[1], 7)) + ' ' + str(np.round(p[2], 7))
    while len(vertex_line) < 31:
        vertex_line += ' '
    vertex_line += '# Vertex ' + str(i)
    obj_lines.append(vertex_line)

obj_lines.append('')
line = ''
for i in range(32):
    line += '#'
line += ' Faces\n'
obj_lines.append(line)

for nm in new_mtls:
    obj_lines.append(f"usemtl {nm}")
    for a,b,c in builder.faces[nm]:
        obj_lines.append(f"f {a+1} {b+1} {c+1}")

obj_text = '\n'.join(obj_lines)

def write_or_print(path: Path, text: str, label: str):
    try:
        path.write_text(text, encoding="utf-8"); return True
    except Exception:
        print(f"\n===== BEGIN {label} =====\n{text}\n===== END {label} =====\n"); return False

num_patches = len(new_mtls)
new_folder_path = Path("../Museum_{}_patches".format(num_patches))
if not os.path.isdir(new_folder_path):
    os.mkdir(new_folder_path)

# I/O (relative to working dir)
OBJ_OUT = Path("../Museum_{}_patches/mesh.obj".format(num_patches))
MTL_OUT = Path("../Museum_{}_patches/mesh.mtl".format(num_patches))

ok1 = write_or_print(MTL_OUT, mtl_text, "mesh.mtl")
ok2 = write_or_print(OBJ_OUT, obj_text, "mesh.obj")
print("Wrote files." if (ok1 and ok2) else "Printed contents (write blocked).")
